# NumPy Projects

## 1. Basic Statistics Calculator
### Objective: Use NumPy to compute mean, median, and standard deviation from a list of numbers.

In [103]:
import numpy as np
data=np.array([12,34,15,26,24,65,345])

print("Mean=",np.mean(data))
print("Median=",np.median(data))
print("Standard Deviation=",np.std(data))

Mean= 74.42857142857143
Median= 26.0
Standard Deviation= 111.64338268773113


## 2. Matrix Multiplication
### Objective: Multiply two matrices using NumPy.

In [29]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[12,13,14],[15,16,14],[10,20,30]])

result=np.dot(A , B)
print('Matrix Product=\n',result)

Matrix Product=
 [[ 72 105 132]
 [183 252 306]]


## 3. Normalize a Dataset
### Objective: Scale all values between 0 and 1.

In [37]:
data = np.array([10, 15, 20, 25, 30])
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Normalized:", normalized)

Normalized: [0.   0.25 0.5  0.75 1.  ]


## 4. Student Grades Analysis
### Objective: Create a 2D array where rows are students and columns are subjects to calculate the average score per student & average score per subject.

In [111]:
import numpy as np
grades = np.array([
    [85, 78, 92],
    [56, 64, 70],
    [90, 88, 75],
    [30, 45, 40],
    [100, 95, 98]])
# Average score per student
avg_student = grades.mean(axis=1)
print("Average score per student:\n", avg_student)
# Average score per subject
avg_subject = grades.mean(axis=0)
print("Average score per subject:\n", avg_subject)

Average score per student:
 [85.         63.33333333 84.33333333 38.33333333 97.66666667]
Average score per subject:
 [72.2 74.  75. ]


## 5. Missing Data Imputation
### Objective: Handle missing values in a dataset.
#### Tasks:
#### i. Create a 2D array with random numbers and introduce some np.nan values.
#### ii. Detect missing values & replace with column mean.

In [114]:
data = np.array([
    [1.0, 2.5, np.nan],
    [4.2, np.nan, 6.3],
    [7.1, 8.8, 9.0]])

# Detect missing values
print("Missing Values:\n", np.isnan(data))
# Replace with column mean
col_means = np.nanmean(data, axis=0)
print(col_means)

Missing Values:
 [[False False  True]
 [False  True False]
 [False False False]]
[4.1  5.65 7.65]
